/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starpew;

import com.almasb.fxgl.app.GameApplication;
import com.almasb.fxgl.app.GameSettings;
import com.almasb.fxgl.dsl.FXGL;
import com.almasb.fxgl.entity.Entity;
import com.almasb.fxgl.input.KeyTrigger;
import com.almasb.fxgl.input.Trigger;
import com.almasb.fxgl.input.TriggerListener;
import com.almasb.fxgl.input.UserAction;
import javafx.scene.input.KeyCode;

public class SpriteSheetAnimationApp extends GameApplication {

    private Entity player;
    private KeyCode lastKeyPressed;

    @Override
    protected void initSettings(GameSettings settings) {

    }

    @Override
    protected void initGame() {
        FXGL.getGameWorld().addEntityFactory(new StarpewFactory());

        player = FXGL.getGameWorld().spawn("player");
    }

    @Override
    protected void initInput() {
        FXGL.getInput().addAction(new UserAction("Right") {
            @Override
            protected void onAction() {
                player.getComponent(AnimationComponent.class).moveRight();
            }

            @Override
            protected void onActionEnd() {
                player.getComponent(AnimationComponent.class).stop();
            }

        }, KeyCode.D);

        FXGL.getInput().addAction(new UserAction("Left") {

            @Override
            protected void onAction() {
                player.getComponent(AnimationComponent.class).moveLeft();
            }

            @Override
            protected void onActionEnd() {
                player.getComponent(AnimationComponent.class).stop();
            }

        }, KeyCode.A);

        FXGL.getInput().addAction(new UserAction("Down") {

            @Override
            protected void onAction() {
                player.getComponent(AnimationComponent.class).moveDown();
            }

            @Override
            protected void onActionEnd() {
                player.getComponent(AnimationComponent.class).stop();
            }

        }, KeyCode.S);

        FXGL.getInput().addAction(new UserAction("Up") {
            @Override
            protected void onAction() {
                player.getComponent(AnimationComponent.class).moveUp();
            }

            @Override
            protected void onActionEnd() {
                player.getComponent(AnimationComponent.class).stop();
            }

        }, KeyCode.W);

        FXGL.getInput().addTriggerListener(new TriggerListener() {
            @Override
            protected void onActionBegin(Trigger trigger) {
                if (trigger.isKey()) {
                    var keyTrigger = (KeyTrigger) trigger;
                    lastKeyPressed = keyTrigger.getKey();
                    System.out.println("last key pressed: " + lastKeyPressed);
                }
            }

            @Override
            protected void onAction(Trigger trigger) {
                if (trigger.isKey()) {
                    var keyTrigger = (KeyTrigger) trigger;

                    // key is being pressed now
                    var key = keyTrigger.getKey();
                }

                System.out.println("On: " + trigger);
            }

            @Override
            protected void onActionEnd(Trigger trigger) {
                System.out.println("End: " + trigger);
            }
        });
    }

    public static void main(String[] args) {
        launch(args);
    }
}