/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starpewValley;

import org.junit.Test;

import starpew.SpriteSheetAnimationApp;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        SpriteSheetAnimationApp classUnderTest = new SpriteSheetAnimationApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
